#server:
#  port: 9090
spring:
  messages:
    basename: i18n/messages
http:
  port: 80
#https端口号.
server:
  port: 443
  #证书的路径.
  ssl:
    key-store: classpath:keystore.p12
    #证书密码，请修改为您自己证书的密码.
    key-store-password: qwer1234
    #秘钥库类型
    keyStoreType: PKCS12
    #证书别名
    keyAlias: tomcat
# keytool -genkey -alias tomcat -dname "CN=Dazhi,OU=大智的小站,O=大智Demo,L=HaiDian,ST=BeiJing,C=CN" -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 365
